@echo off
cd %~dp0
rem cd b:\sources\AzureDevOps-MCP
rem npm run build
rem npm run start

set ALLOWED_TOOLS=listPullRequests,getPullRequest,getPullRequestComments,approvePullRequest,mergePullRequest,addPullRequestInlineComment,addPullRequestFileComment,addPullRequestComment,getPullRequestFileChanges,getPullRequestChangesCount,getAllPullRequestChanges,getFileContent,browseRepository,getCommitHistory,azureDevOpsWorkItems,addWorkItemComment,assignWorkItem,bulkCreateWorkItems,convertFindingsToWorkItems,createArea,createIteration,createWorkItem,getCurrentSprint,getIterations,getSprints,getSprintWorkItems,getTeamMembers,getTeams,getWorkItemById,getWorkItemTypeFields,getWorkItemTypes,listWorkItems,searchWorkItems,updateWorkItem,updateWorkItemState,listRepositories

node %~dp0\dist\index.js
exit

